server:
  port: 10005
spring:
  redis:
    host: 39.108.149.230
    database: 0
    port: 6379
    password: CPC@2021
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.12.2.202:3306/mall?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: mall
    password: pa2sw0rd
  application:
    name: mall-admin
  boot:
    admin:
      client:
        url: http://1.116.200.39:8059
  zipkin:
    enabled: true
    discovery-client-enabled: true
    base-url: 'http://39.108.149.230:9411'
  sleuth:
    sampler:
      probability: 1
      rate: 10
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: full
